-- depends_on: test.incremental_appsflyer_events_default_in_app_events
SELECT
    toLowCardinality(attributed_touch_type) AS touch_type,
    toDateTime32(attributed_touch_time) AS touch_time,
    toDateTime32(install_time) AS install_time,
    toDateTime32(event_time) AS event_time,
    toLowCardinality(event_name) AS event_name,
    toLowCardinality(event_source) AS event_source,
    toLowCardinality(af_prt) AS partner,
    toLowCardinality(media_source) AS media_source,
    toLowCardinality(campaign) AS campaign,
    af_siteid AS site_id,
    af_ad AS ad,                                            
    toLowCardinality(country_code) AS country_code,
    toLowCardinality(city) AS city,   
    appsflyer_id,
    customer_user_id AS custom_uid,
    toLowCardinality(platform) AS platform,
    toLowCardinality(is_retargeting) AS is_retargeting,                  
    toLowCardinality(is_primary_attribution) AS is_primary_attribution,  
    __emitted_at,
    toLowCardinality(__table_name) AS __table_name,
    toLowCardinality('&&&') AS __link                                    
FROM (
    

        (
            select
                cast('test.incremental_appsflyer_events_default_in_app_events' as String) as _dbt_source_relation,

                
                    cast("__date" as Date) as "__date" ,
                    cast("ad_unit" as String) as "ad_unit" ,
                    cast("advertising_id" as String) as "advertising_id" ,
                    cast("af_ad" as String) as "af_ad" ,
                    cast("af_ad_id" as String) as "af_ad_id" ,
                    cast("af_ad_type" as String) as "af_ad_type" ,
                    cast("af_adset" as String) as "af_adset" ,
                    cast("af_adset_id" as String) as "af_adset_id" ,
                    cast("af_attribution_lookback" as String) as "af_attribution_lookback" ,
                    cast("af_c_id" as String) as "af_c_id" ,
                    cast("af_channel" as String) as "af_channel" ,
                    cast("af_cost_currency" as String) as "af_cost_currency" ,
                    cast("af_cost_model" as String) as "af_cost_model" ,
                    cast("af_cost_value" as String) as "af_cost_value" ,
                    cast("af_keywords" as String) as "af_keywords" ,
                    cast("af_prt" as String) as "af_prt" ,
                    cast("af_reengagement_window" as String) as "af_reengagement_window" ,
                    cast("af_siteid" as String) as "af_siteid" ,
                    cast("af_sub1" as String) as "af_sub1" ,
                    cast("af_sub2" as String) as "af_sub2" ,
                    cast("af_sub3" as String) as "af_sub3" ,
                    cast("af_sub4" as String) as "af_sub4" ,
                    cast("af_sub5" as String) as "af_sub5" ,
                    cast("af_sub_siteid" as String) as "af_sub_siteid" ,
                    cast("amazon_aid" as String) as "amazon_aid" ,
                    cast("android_id" as String) as "android_id" ,
                    cast("app_id" as String) as "app_id" ,
                    cast("app_name" as String) as "app_name" ,
                    cast("app_type" as String) as "app_type" ,
                    cast("app_version" as String) as "app_version" ,
                    cast("appsflyer_id" as String) as "appsflyer_id" ,
                    cast("att" as String) as "att" ,
                    cast("attributed_touch_time" as String) as "attributed_touch_time" ,
                    cast("attributed_touch_type" as String) as "attributed_touch_type" ,
                    cast("blocked_reason" as String) as "blocked_reason" ,
                    cast("blocked_reason_rule" as String) as "blocked_reason_rule" ,
                    cast("blocked_reason_value" as String) as "blocked_reason_value" ,
                    cast("blocked_sub_reason" as String) as "blocked_sub_reason" ,
                    cast("bundle_id" as String) as "bundle_id" ,
                    cast("campaign" as String) as "campaign" ,
                    cast("campaign_type" as String) as "campaign_type" ,
                    cast("carrier" as String) as "carrier" ,
                    cast("city" as String) as "city" ,
                    cast("contributor1_af_prt" as String) as "contributor1_af_prt" ,
                    cast("contributor1_campaign" as String) as "contributor1_campaign" ,
                    cast("contributor1_match_type" as String) as "contributor1_match_type" ,
                    cast("contributor1_media_source" as String) as "contributor1_media_source" ,
                    cast("contributor1_touch_time" as String) as "contributor1_touch_time" ,
                    cast("contributor1_touch_type" as String) as "contributor1_touch_type" ,
                    cast("contributor2_af_prt" as String) as "contributor2_af_prt" ,
                    cast("contributor2_campaign" as String) as "contributor2_campaign" ,
                    cast("contributor2_match_type" as String) as "contributor2_match_type" ,
                    cast("contributor2_media_source" as String) as "contributor2_media_source" ,
                    cast("contributor2_touch_time" as String) as "contributor2_touch_time" ,
                    cast("contributor2_touch_type" as String) as "contributor2_touch_type" ,
                    cast("contributor3_af_prt" as String) as "contributor3_af_prt" ,
                    cast("contributor3_campaign" as String) as "contributor3_campaign" ,
                    cast("contributor3_match_type" as String) as "contributor3_match_type" ,
                    cast("contributor3_media_source" as String) as "contributor3_media_source" ,
                    cast("contributor3_touch_time" as String) as "contributor3_touch_time" ,
                    cast("contributor3_touch_type" as String) as "contributor3_touch_type" ,
                    cast("conversion_type" as String) as "conversion_type" ,
                    cast("country_code" as String) as "country_code" ,
                    cast("custom_data" as String) as "custom_data" ,
                    cast("customer_user_id" as String) as "customer_user_id" ,
                    cast("deeplink_url" as String) as "deeplink_url" ,
                    cast("device_category" as String) as "device_category" ,
                    cast("device_download_time" as String) as "device_download_time" ,
                    cast("device_model" as String) as "device_model" ,
                    cast("device_type" as String) as "device_type" ,
                    cast("dma" as String) as "dma" ,
                    cast("event_name" as String) as "event_name" ,
                    cast("event_revenue" as String) as "event_revenue" ,
                    cast("event_revenue_currency" as String) as "event_revenue_currency" ,
                    cast("event_revenue_usd" as String) as "event_revenue_usd" ,
                    cast("event_source" as String) as "event_source" ,
                    cast("event_time" as String) as "event_time" ,
                    cast("event_value" as String) as "event_value" ,
                    cast("gp_broadcast_referrer" as String) as "gp_broadcast_referrer" ,
                    cast("gp_click_time" as String) as "gp_click_time" ,
                    cast("gp_install_begin" as String) as "gp_install_begin" ,
                    cast("gp_referrer" as String) as "gp_referrer" ,
                    cast("http_referrer" as String) as "http_referrer" ,
                    cast("idfa" as String) as "idfa" ,
                    cast("idfv" as String) as "idfv" ,
                    cast("imei" as String) as "imei" ,
                    cast("impressions" as String) as "impressions" ,
                    cast("install_app_store" as String) as "install_app_store" ,
                    cast("install_time" as String) as "install_time" ,
                    cast("ip" as String) as "ip" ,
                    cast("is_lat" as String) as "is_lat" ,
                    cast("is_primary_attribution" as String) as "is_primary_attribution" ,
                    cast("is_receipt_validated" as String) as "is_receipt_validated" ,
                    cast("is_retargeting" as String) as "is_retargeting" ,
                    cast("keyword_id" as String) as "keyword_id" ,
                    cast("keyword_match_type" as String) as "keyword_match_type" ,
                    cast("language" as String) as "language" ,
                    cast("match_type" as String) as "match_type" ,
                    cast("media_source" as String) as "media_source" ,
                    cast("mediation_network" as String) as "mediation_network" ,
                    cast("monetization_network" as String) as "monetization_network" ,
                    cast("network_account_id" as String) as "network_account_id" ,
                    cast("oaid" as String) as "oaid" ,
                    cast("operator" as String) as "operator" ,
                    cast("original_url" as String) as "original_url" ,
                    cast("os_version" as String) as "os_version" ,
                    cast("placement" as String) as "placement" ,
                    cast("platform" as String) as "platform" ,
                    cast("postal_code" as String) as "postal_code" ,
                    cast("region" as String) as "region" ,
                    cast("rejected_reason" as String) as "rejected_reason" ,
                    cast("rejected_reason_value" as String) as "rejected_reason_value" ,
                    cast("retargeting_conversion_type" as String) as "retargeting_conversion_type" ,
                    cast("sdk_version" as String) as "sdk_version" ,
                    cast("segment" as String) as "segment" ,
                    cast("state" as String) as "state" ,
                    cast("store_reinstall" as String) as "store_reinstall" ,
                    cast("user_agent" as String) as "user_agent" ,
                    cast("wifi" as String) as "wifi" ,
                    cast("__table_name" as String) as "__table_name" ,
                    cast("__emitted_at" as DateTime) as "__emitted_at" ,
                    cast("__normalized_at" as DateTime) as "__normalized_at" 

            from test.incremental_appsflyer_events_default_in_app_events

            
        )

        )


