-- depends_on: test.join_appmetrica_events
-- depends_on: test.join_ym_events
SELECT * REPLACE(toLowCardinality(__table_name) AS __table_name)
FROM (

(
SELECT
        toDateTime("__date") as __date ,
        toString("__table_name") as __table_name ,
        toDateTime("event_datetime") as event_datetime ,
        toString("accountName") as accountName ,
        toString("appmetricaDeviceId") as appmetricaDeviceId ,
        toString("mobileAdsId") as mobileAdsId ,
        toString("crmUserId") as crmUserId ,
        toString("promoCode") as promoCode ,
        toString("osName") as osName ,
        toString("cityName") as cityName ,
        toString("adSourceDirty") as adSourceDirty ,
        toString("utmSource") as utmSource ,
        toString("utmMedium") as utmMedium ,
        toString("utmCampaign") as utmCampaign ,
        toString("utmTerm") as utmTerm ,
        toString("utmContent") as utmContent ,
        toString("transactionId") as transactionId ,
        toString("utmHash") as utmHash ,
        toUInt8("sessions") as sessions ,
        toUInt8("addToCartSessions") as addToCartSessions ,
        toUInt8("cartViewSessions") as cartViewSessions ,
        toUInt8("checkoutSessions") as checkoutSessions ,
        toUInt8("webSalesSessions") as webSalesSessions ,
        toUInt8("sales") as sales ,
        toFloat64("amountSales") as amountSales ,
        toUInt8("registrationCardSessions") as registrationCardSessions ,
        toUInt8("registrationButtonClick") as registrationButtonClick ,
        toUInt8("linkingCardToPhoneNumberSessions") as linkingCardToPhoneNumberSessions ,
        toUInt8("registrationLendingPromotionsSessions") as registrationLendingPromotionsSessions ,
        toUInt8("registrationCashbackSessions") as registrationCashbackSessions ,
        toUInt8("instantDiscountActivationSessions") as instantDiscountActivationSessions ,
        toUInt8("couponActivationSessions") as couponActivationSessions ,
        toUInt8("participationInLotterySessions") as participationInLotterySessions ,
        toUInt8("pagesViews") as pagesViews ,
        toUInt64("screenView") as screenView ,
        toUInt8("installApp") as installApp ,
        toUInt8("installs") as installs ,
        toString("installationDeviceId") as installationDeviceId ,
        toDateTime("__emitted_at") as __emitted_at ,
        toString("__link") as __link ,
        toString('') as touch_type ,
        toDateTime(0) as touch_time ,
        toDateTime(0) as install_time ,
        toDateTime(0) as event_time ,
        toString('') as event_name ,
        toString('') as event_source ,
        toString('') as partner ,
        toString('') as media_source ,
        toString('') as campaign ,
        toString('') as site_id ,
        toString('') as ad ,
        toString('') as country_code ,
        toString('') as city ,
        toString('') as appsflyer_id ,
        toString('') as custom_uid ,
        toString('') as platform ,
        toString('') as is_retargeting ,
        toString('') as is_primary_attribution ,
        toString('') as visitId ,
        toString('') as clientId ,
        toString('') as cityCode ,
        toUInt32(0) as pageViews 
FROM test.join_appmetrica_events
)

UNION ALL


(
SELECT
        toDateTime(0) as __date ,
        toString("__table_name") as __table_name ,
        toDateTime(0) as event_datetime ,
        toString('') as accountName ,
        toString('') as appmetricaDeviceId ,
        toString('') as mobileAdsId ,
        toString('') as crmUserId ,
        toString('') as promoCode ,
        toString('') as osName ,
        toString('') as cityName ,
        toString('') as adSourceDirty ,
        toString('') as utmSource ,
        toString('') as utmMedium ,
        toString('') as utmCampaign ,
        toString('') as utmTerm ,
        toString('') as utmContent ,
        toString('') as transactionId ,
        toString('') as utmHash ,
        toUInt8(0) as sessions ,
        toUInt8(0) as addToCartSessions ,
        toUInt8(0) as cartViewSessions ,
        toUInt8(0) as checkoutSessions ,
        toUInt8(0) as webSalesSessions ,
        toUInt8(0) as sales ,
        toFloat64(0) as amountSales ,
        toUInt8(0) as registrationCardSessions ,
        toUInt8(0) as registrationButtonClick ,
        toUInt8(0) as linkingCardToPhoneNumberSessions ,
        toUInt8(0) as registrationLendingPromotionsSessions ,
        toUInt8(0) as registrationCashbackSessions ,
        toUInt8(0) as instantDiscountActivationSessions ,
        toUInt8(0) as couponActivationSessions ,
        toUInt8(0) as participationInLotterySessions ,
        toUInt8(0) as pagesViews ,
        toUInt64(0) as screenView ,
        toUInt8(0) as installApp ,
        toUInt8(0) as installs ,
        toString('') as installationDeviceId ,
        toDateTime("__emitted_at") as __emitted_at ,
        toString("__link") as __link ,
        toString("touch_type") as touch_type ,
        toDateTime("touch_time") as touch_time ,
        toDateTime("install_time") as install_time ,
        toDateTime("event_time") as event_time ,
        toString("event_name") as event_name ,
        toString("event_source") as event_source ,
        toString("partner") as partner ,
        toString("media_source") as media_source ,
        toString("campaign") as campaign ,
        toString("site_id") as site_id ,
        toString("ad") as ad ,
        toString("country_code") as country_code ,
        toString("city") as city ,
        toString("appsflyer_id") as appsflyer_id ,
        toString("custom_uid") as custom_uid ,
        toString("platform") as platform ,
        toString("is_retargeting") as is_retargeting ,
        toString("is_primary_attribution") as is_primary_attribution ,
        toString('') as visitId ,
        toString('') as clientId ,
        toString('') as cityCode ,
        toUInt32(0) as pageViews 
FROM test.join_appsflyer_events
)

UNION ALL


(
SELECT
        toDateTime("__date") as __date ,
        toString("__table_name") as __table_name ,
        toDateTime(0) as event_datetime ,
        toString('') as accountName ,
        toString('') as appmetricaDeviceId ,
        toString('') as mobileAdsId ,
        toString('') as crmUserId ,
        toString("promoCode") as promoCode ,
        toString("osName") as osName ,
        toString("cityName") as cityName ,
        toString("adSourceDirty") as adSourceDirty ,
        toString("utmSource") as utmSource ,
        toString("utmMedium") as utmMedium ,
        toString("utmCampaign") as utmCampaign ,
        toString("utmTerm") as utmTerm ,
        toString("utmContent") as utmContent ,
        toString("transactionId") as transactionId ,
        toString("utmHash") as utmHash ,
        toUInt8("sessions") as sessions ,
        toUInt8("addToCartSessions") as addToCartSessions ,
        toUInt8("cartViewSessions") as cartViewSessions ,
        toUInt8("checkoutSessions") as checkoutSessions ,
        toUInt8("webSalesSessions") as webSalesSessions ,
        toUInt8("sales") as sales ,
        toFloat64(0) as amountSales ,
        toUInt8("registrationCardSessions") as registrationCardSessions ,
        toUInt8(0) as registrationButtonClick ,
        toUInt8("linkingCardToPhoneNumberSessions") as linkingCardToPhoneNumberSessions ,
        toUInt8("registrationLendingPromotionsSessions") as registrationLendingPromotionsSessions ,
        toUInt8("registrationCashbackSessions") as registrationCashbackSessions ,
        toUInt8(0) as instantDiscountActivationSessions ,
        toUInt8("couponActivationSessions") as couponActivationSessions ,
        toUInt8("participationInLotterySessions") as participationInLotterySessions ,
        toUInt8(0) as pagesViews ,
        toUInt64(0) as screenView ,
        toUInt8(0) as installApp ,
        toUInt8(0) as installs ,
        toString('') as installationDeviceId ,
        toDateTime("__emitted_at") as __emitted_at ,
        toString("__link") as __link ,
        toString('') as touch_type ,
        toDateTime(0) as touch_time ,
        toDateTime(0) as install_time ,
        toDateTime(0) as event_time ,
        toString('') as event_name ,
        toString('') as event_source ,
        toString('') as partner ,
        toString('') as media_source ,
        toString('') as campaign ,
        toString('') as site_id ,
        toString('') as ad ,
        toString('') as country_code ,
        toString('') as city ,
        toString('') as appsflyer_id ,
        toString('') as custom_uid ,
        toString('') as platform ,
        toString('') as is_retargeting ,
        toString('') as is_primary_attribution ,
        toString("visitId") as visitId ,
        toString("clientId") as clientId ,
        toString("cityCode") as cityCode ,
        toUInt32("pageViews") as pageViews 
FROM test.join_ym_events
)

) 
